### ISSUE TITLE
Cannot move active survey to 'Paused' or 'Completed'

### ISSUE THREAD

**Issue by scott-eth** [formbricks/formbricks#6946]
### Issue Summary

We've been using a Form for ~4 months to gather responses and wish to close submissions now. 

We're unable to move the forms state to 'Paused' or 'Completed' — the error `blocksundefined` is returned. 

### Expected Behavior

We can Pause or Complete submissions for the form. 

### Other information (incl. screenshots, Formbricks version, steps to reproduce,...)

<img width="1695" height="188" alt="Image" src="https://github.com/user-attachments/assets/5a1bbecb-560d-42dc-9a3d-093c80ec00c1" />

### Your Environment

Formbricks Cloud (app.formbricks.com)

**Comment by jobenjada** [comment]
hey scott, that's odd, we've fixed the bug in the most recent release 🤔 let us double check!

**Comment by scott-eth** [comment]
Hey, following up on this.

I tried to edit our Form and encountered the following:

1. When attempting to save the form, `Invalid URL` toast is shown

<img width="240" height="94" alt="Image" src="https://github.com/user-attachments/assets/7b4e4787-7c6d-40a2-a28c-0ab2610a626d" />

2. The external button is active, but is now uneditable (could this be causing the issue?)

<img width="1077" height="229" alt="Image" src="https://github.com/user-attachments/assets/235992eb-b69d-4be0-b10c-81d3d0b8d522" />

**Comment by jobenjada** [comment]
hey Scott, no, the invalid URL is a ZOD error that we will fix with a data migration shortly (cc @mattinannt )

The button URL not being editable anymore is because we've had a series of phishing incidents on our platform so we had to move this functionality behind the paywall for Formbricks Cloud (it's still free for on premise instances). Feel free to send me an email to johannes@formbricks.com for a significant discount on the startup plan.

**Comment by scott-eth** [comment]
Thanks @jobenjada – but the original issue still remains; I can't Complete or Pause this survey. 

Any update on the `blocksundefined` issue?

**Comment by jobenjada** [comment]
This is the same issue, we will get it fixed tomorrow morning CET - thanks for your patience!

**Comment by kamaleshbasu** [comment]
@jobenjada any updates on the fix?

**Comment by jobenjada** [comment]
@kamaleshbasu can you check on your end? it should be fixed

**Comment by kamaleshbasu** [comment]
@jobenjada I am self-hosting and still seeing the error since 4.3.2.

**Comment by jobenjada** [comment]
ahh right, we couldn't release it yet because with a migration it needs to be a minor release and we couldn't squeeze in a full QA process. We are working to get a release out next week inshallah

The issue is that your survey has an empty string in a URL field. Did you upload a file or have a URL field in a Thank You card or CTA field? You could try to delete the corresponding element and recreate it to resolve the issue before the release. Sorry for the bug!

**Comment by kamaleshbasu** [comment]
@jobenjada cheers. Ty. Appreciate the fix.

**Comment by scott-eth** [comment]
Resolved for me also! Thanks @jobenjada
